# Generated by Django 5.0.3 on 2024-03-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_a', models.CharField(max_length=100)),
                ('point_b', models.CharField(max_length=100)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('time', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
